os: linux
dist: xenial
language: java
env:
  - XML_DIRECTORY="HGV_trans_EpiDoc" EPIDOC_VERSION="8.13"
  - XML_DIRECTORY="HGV_meta_EpiDoc" EPIDOC_VERSION="8.13"
  - XML_DIRECTORY="DDB_EpiDoc_XML" EPIDOC_VERSION="8.16"
  - XML_DIRECTORY="APIS" EPIDOC_VERSION="8.13"
  - XML_DIRECTORY="DCLP" EPIDOC_VERSION="8.23"
addons:
  apt:
    packages:
    - moreutils
    - parallel
script:
  - java -jar Validation/jing.jar Validation/rdfxml.rng RDF/collection.rdf
  - find $XML_DIRECTORY -name "*.xml" | parallel --gnu --will-cite -X -j8 -u "java -jar Validation/jing.jar Validation/EpiDoc/${EPIDOC_VERSION}/tei-epidoc.rng {}"
